#!/bin/bash

if [ "$EUID" -ne 0  ]
then
	echo "Pls root"
	exit
fi

SERVER_PATH="/home/user/apdc/server/attestation_tpm"

############### REMOVE ###############
#remove quote tools
cd $SERVER_PATH/tpm-quote-tools-1.0.2/ &&\
sudo make uninstall &&\
sudo make clean

#remove trousers and companhia
sudo apt-get remove -y libtspi* tpm-tools trousers &&\
sudo apt-get autoremove && sudo apt-get autoclean && sudo apt-get update

#remove tpm emulator
cd $SERVER_PATH/tpm-emulator-master/ &&\
cd build/ &&\
sudo make uninstall &&\
sudo make clean &&\
cd .. &&\
sudo rm -rf build

############### INSTALL ###############
#install tpm-emulator
sudo apt-get -y install libgmp3-dev
cd $SERVER_PATH/tpm-emulator-master/
mkdir build
cd build/
cmake ../
make #pode ser preciso linux-headers sudo apt-get install linux-headers-$(uname -r)
sudo make install 
sudo depmod -a
sudo modprobe tpmd_dev

#fazer restart
sudo modprobe tpmd_dev
sudo tpmd -f &

sudo apt-get -y install trousers
sudo chown tss /dev/tpm0
sudo chgrp tss /dev/tpm0
gksu gedit /etc/init.d/trousers
# http://stackoverflow.com/questions/21957979/installing-trousers-for-tpm-emulator
# e tirar o chuid
sudo apt-get -y install trousers
sudo apt-get -y install tpm-tools
sudo apt-get -y install libtspi-dev libtspi1


tpm_version 
cd $SERVER_PATH/tpm-quote-tools-1.0.2/
./configure 
make
make check
sudo make install
make installcheck

#installation finished, start services

sudo $SERVER_PATH/../run_tpm.sh

tpm_clear --force
tpm_setenable --enable --force
tpm_setactive --active

tpm_takeownership -z -y

#cd ../data/
#dir
#tpm_mkaik 
#tpm_mkaik -z aikblob pubkey
